//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddCalendarAppointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int id { get; set; }
        public Nullable<int> appointment_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual appointment appointment { get; set; }
        public virtual user user { get; set; }
    }
}
